name: pnpm Example Workflow

on:
  push:
    branches: [ 'master' ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Vite
        run: npm install -g vite

      - name: Install dependencies
        working-directory: front
        run: pnpm install

      - name: Build
        working-directory: front
        run: tsc && vite build

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        working-directory: front
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
